import { useActor } from '@xstate/react'
import type { NextPage } from 'next'
import dynamic from 'next/dynamic'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useContext, useEffect } from 'react'
import { createConnection } from '../../hooks/useEvaluatorState'
import { ServerMessage } from '../../types'

const ws = createConnection();
const Join: NextPage = () => {
  const router = useRouter();
  const code = router.query.code;
  useEffect(() => {
    const sub = ws!.subscribe((msg) => {
      const message = msg as ServerMessage;
      if (message.message === 'GAME_START') {
          const { withMachine } = message.payload;
          if (withMachine) {
              router.push(`/snake/${code}`);
          } else {
              router.push(`/chat-human/${code}`);
          }
      }
    });

    return () => sub.unsubscribe();
  }, [router, code]);

  return (
    <div>
      <Head>
        <title>Turing Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      JOIN
      <div>{code}</div>
      <button onClick={() => ws?.next({ message: 'JOIN', payload: { code }})}>Click to join</button>
    </div>
  );
}

export default dynamic(() => Promise.resolve(Join), { ssr: false });
