import type { NextPage } from 'next'
import dynamic from 'next/dynamic'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useContext, useEffect } from 'react'
import { WebsocketContext } from '../../providers/WebSocketProvider'
import { ServerMessage } from '../../types'

const HumanChat: NextPage = () => {
  const { connection, sendMsg } = useContext(WebsocketContext);
  const router = useRouter();
  const code = router.query.code;
  useEffect(() => {
      if (code != null && sendMsg != null) {
          sendMsg({ message: 'RECONNECT', payload: { code, isEvaluator: false}});
      }
  }, [code, sendMsg]);
  useEffect(() => {
    const sub = connection!.subscribe((msg) => {
        console.log(msg);
      const message = msg as ServerMessage;
      if (message.message === 'GAME_START') {
        router.push(`/chat/${code}`);
      }
    });

    return () => sub.unsubscribe();
  }, [router, code, connection]);

  return (
    <div>
      <Head>
        <title>Turing Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Chat
      <button onClick={() => sendMsg({ message: 'MESSAGE', payload: { code, fromEvaluator: false, text: 'elo123'}})}>Send Msg</button>
    </div>
  );
}

export default dynamic(() => Promise.resolve(HumanChat), { ssr: false });
